export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_POPULATE = 'PRODUCTS_POPULATE';

export const PRODUCTS_FILTER_SET = 'PRODUCTS_FILTER_SET';
export const SELECTED_PRODUCT_SET = 'SELECTED_PRODUCT_SET';

export const PRODUCTS_FILTER_VALUE_DATE_ORDER = 'PRODUCTS_FILTER_VALUE_DATE_ORDER';
export const PRODUCTS_FILTER_VALUE_TYPE = 'PRODUCTS_FILTER_VALUE_TYPE';
