export const CATEGORY_FILM_ID = 2;
export const CATEGORY_WEB_ID = 1;

export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_POPULATE = 'PRODUCTS_POPULATE';

export const PRODUCTS_FILTER_SET = 'PRODUCTS_FILTER_SET';
export const SELECTED_PRODUCT_SET = 'SELECTED_PRODUCT_SET';

export const PRODUCTS_FILTER_ALL = 'PRODUCTS_FILTER_ALL';
export const PRODUCTS_FILTER_FILM = 'PRODUCTS_FILTER_FILMS';
export const PRODUCTS_FILTER_WEB = 'PRODUCTS_FILTER_WEB';
